export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div>  
            <h2>Inner Layout</h2>
            {children}
            
        </div>
    )
  }
  